### PR TITLE
fix(backend port number): change backend port number to 6174

### LINKED ISSUE #992: Port 5000 already in use by AirPlay on macOS 12
**Description**
Port 5000 used as the server port in the project is already in use by AirPlay on macOS 12. As such, when I run `npm run dev`, this the following error message is shown:
[ERROR] 14:44:54 Error: listen EADDRINUSE: address already in use :::5000
image

**Additional context**
Brief Googling reveals that this is an issue with Apple using port 5000 for AirPlay Receiver. See [here](https://developer.apple.com/forums/thread/682332) and [here](https://www.reddit.com/r/webdev/comments/qg8yt9/apple_took_over_port_5000_in_the_latest_macos/). 

I don't fully understand this, but apparently this is [not an unreasonable decision](https://www.reddit.com/r/webdev/comments/qg8yt9/comment/hi65w7i/):
> Just did a bit more digging, and IANA actually assigns port 5000 to "commplex-main" - so really any other service that's using that port is violating the official assignment. Based on a quick search of what commplex-main is, it's related to UPnP for network device discoverability. I'm not sure exactly what the AirPlay Receiver service does, but I get the gist that it probably does fit somewhere into the scope of UPnP-related features. At the very least, it's probably a far more accurate usage of port 5000 than some random dev servers.

**Solution**
A quick way to fix the problem is to disable AirPlay Receiver in System Settings > Sharing. 

However, I was thinking a better solution might be to simply use a different port number for the server. If I'm not mistaken, we can just use another port number that is less likely to result in such conflicts? If so, happy to submit a PR to change all instances of 5000 to, say, another randomly chosen port number.

### PR DESCRIPTION
**Pull request by zxt-tzx**
Current port number of 5000 clashes with Apple using port 5000 for AirPlay Receiver on Mac.

fixes #992

Notes:
- Port number of 6174 is somewhat arbitrarily chosen. 
- Not sure if it's possible to make the port number a variable instead (so as to adhere to DRY principle); currently, the port number is repeated across multiple files)

Pros: macOS users don't need to switch off AirPlay. (Useful when, say, trying to use Mac to stream audio/video from iPhone!) 
Cons: Defies convention of using 5000 for ExpressJS. 6174 chosen [somewhat arbitrarily](https://en.wikipedia.org/wiki/6174_(number)).  It also appear [to be unassigned](https://www.adminsub.net/tcp-udp-port-finder/6174).

### CODE REVIEW

**Review by LoneRifle — CHANGES_REQUESTED** [review]
Lgtm otherwise

File: server/src/bootstrap/index.ts [hunk 1]
```diff
@@ -77,7 +77,7 @@ app.use(requestLoggingMiddleware)
 
 // cors enable
 app.options('*', cors<express.Request>())
-app.use(cors({ origin: 'http://localhost:5000' }))
+app.use(cors({ origin: 'http://localhost:6174' }))
```
Comment (LoneRifle) [inline server/src/bootstrap/index.ts]: Have this replaced by `SERVER_PORT` instead

Comment (zxt-tzx) [reply server/src/bootstrap/index.ts]: OK done!

**Review by LoneRifle — APPROVED** [review]
lgtm
