### PR TITLE
fix: remove nested form of linkcontrol

### LINKED ISSUE #110: Adding hyperlink leads back to home page
**Describe the bug**
Adding any hyperlink during creating or editing form leads back to home page after clicking add.

**Expected behavior**
Should add the link and stay on the same page.

https://user-images.githubusercontent.com/20250559/130004716-c5d412f2-423a-470d-ab95-7ecdb943d58a.mov

### PR DESCRIPTION
**Pull request by nauynix**
## Problem

Closes #110 

## Solution

When react was upgraded from v16 to v17, nested form elements no longer fires onSubmit. LinkControl was originally a nested form inside its rich text editor, so this PR removes the form element.
https://github.com/facebook/react/issues/20741

##BEFORE

https://user-images.githubusercontent.com/20250559/130004716-c5d412f2-423a-470d-ab95-7ecdb943d58a.mov

##AFTER

https://user-images.githubusercontent.com/20250559/130023868-935c0932-227e-4ec8-a38c-eec72569214c.mov

### CODE REVIEW

File: client/src/components/RichText/LinkControl.tsx [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import { Box, Button, HStack, Input, Text } from '@chakra-ui/react'
-import React, { useState } from 'react'
+import React, { MouseEventHandler, useState } from 'react'
```
Comment (LoneRifle) [inline client/src/components/RichText/LinkControl.tsx]:
```suggestion
import { MouseEventHandler, useState } from 'react'
```

**Review by LoneRifle — APPROVED** [review]
lgtm otherwise
