### PR TITLE
fix(archived-posts): redirect to /not-found when public post with postId doesn't exist

### LINKED ISSUE #540: Archived questions cannot be viewed by the public, but does not redirect to the not-found page either
**Describe the bug**

Archived questions cannot be viewed by the public, but does not redirect to the not-found page either. E.g. https://ask.gov.sg/questions/484

**To Reproduce**
1. Go to 'https://ask.gov.sg/questions/484'

**Expected behavior**

User should be directed to not found.

**Screenshots**

https://user-images.githubusercontent.com/37061143/136732192-a5b2ddc8-7b63-4ffa-b0d6-e69977254fac.mov

**Additional Context**

Will remove archived questions from Google search console manually first, so that these pages do not show up on google searches (will likely be frustrating for the user if they do)...

### PR DESCRIPTION
**Pull request by LinHuiqing**
## Problem

Archived post pages are still indexed by google search crawlers and do not redirect to not-found page.

Closes #540

## Solution

Modify `getSinglePost` in post service to only query for public posts.

**Features**:

- (post.service) edit sequelize query for getSinglePost to only query for public posts
- (post.service) query for related posts only when post with postId is found

**Improvements**:

- (Post.component) query for answers only when post.id exists

## Before & After Screenshots

**BEFORE**:

Post page is crawled by google search crawler.

When post page is accessed:

https://user-images.githubusercontent.com/37061143/136732192-a5b2ddc8-7b63-4ffa-b0d6-e69977254fac.mov

When checked on FB sharing debugger:

https://user-images.githubusercontent.com/37061143/136763939-1517fbd5-4886-4a86-a3d1-b2be017ff529.mov

**AFTER**:

https://user-images.githubusercontent.com/37061143/136762664-201881b0-4406-4e87-8699-9f4b6c7d95cf.mov

## Tests

0. Find a post page's URL where the post has been archived. Such a post can be found by first creating a post, saving the post page's URL, then deleting the post. The post page URL referred to subsequent steps would be the URL found in this step.
1. Try to access the post page. You should be redirected to /not-found.
2. On [FB Sharing Debugger](https://developers.facebook.com/tools/debug/), debug the URL found. The response code should be 404 and all the other details should be the same as other invalid URLs.

### CODE REVIEW

File: client/src/pages/Post/Post.component.jsx [hunk 1]
```diff
@@ -75,6 +76,7 @@ const Post = () => {
   const { _, data: answers } = useQuery(
     [GET_ANSWERS_FOR_POST_QUERY_KEY, post?.id],
     () => getAnswersForPost(post?.id),
+    { enabled: !!post?.id },
```
Comment (LoneRifle) [inline client/src/pages/Post/Post.component.jsx]:
```suggestion
    { enabled: Boolean(post?.id) },
```

**Review by LoneRifle — APPROVED** [review]
lgtm otherwise

File: client/src/pages/Post/Post.component.jsx (hunk 1 above)
Comment (LinHuiqing) [reply client/src/pages/Post/Post.component.jsx]: okays done
