### PR TITLE
fix(askform): fix topic re-selection bug, migrate to Chakra

### LINKED ISSUE #748: Topic needs to be selected again when editing a post
**Describe the bug**
When a user edits a post, the "Please select a topic" error will pop up if the topic is left as the default. The user will need to click that same topic again before submitting.

**To Reproduce**
1. Log in
2. Choose a post, click 'edit'
3. Click 'Confirm changes' directly

**Expected behavior**
The "Please select a topic" error should not pop up if the topic is left as the default.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by wanlingt**
## Problem

When a user edits a post, the "Please select a topic" error will pop up if the topic is left as the default. The user will need to click that same topic again before submitting.

Closes #748 

## Solution
- Move away from using `defaultValue` in the select component, instead use `defaultValues` in useForm. Rely on `value` to provide the selection
- Migrate styling to Chakra theme

## Before & After Screenshots

**BEFORE**:

https://user-images.githubusercontent.com/56983748/143334230-7a439979-fa6a-4539-92c3-c92d9cf09a84.mov

**AFTER**:

Edit post:

https://user-images.githubusercontent.com/56983748/143334238-36ed17f4-5bc3-4d4e-8d32-187838e26648.mov

Add post:

https://user-images.githubusercontent.com/56983748/143334250-72ddab95-929e-44f7-9d61-3b64b4730c10.mov

## Tests

- Create a new post
- When editing a post, no topic selection error should pop up if the topic is left as it is

### CODE REVIEW

File: client/src/pages/EditForm/EditForm.component.tsx [hunk 1]
```diff
@@ -63,11 +61,8 @@ const EditForm = (): JSX.Element => {
       },
     )
     const topicId = Number(postData?.topicId)
-    const { isLoading: isPostTopicLoading, data: postTopic } = useQuery(
-      GET_TOPIC_BY_ID_QUERY_KEY,
-      () => getTopicById(topicId),
-      { enabled: !!topicId },
-    )
+    const postTopic = topicData?.filter((topic) => topic.id === topicId)
+
```
Comment (LoneRifle) [inline client/src/pages/EditForm/EditForm.component.tsx:65]: Good catch!

File: client/src/theme/components/AskForm.tsx [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+    cancelButton: {
+      //textStyle is not used due to a bug in Chakra UI (Issue #3884)
+      font: 'inter',
+      fontSize: '16px',
+      fontWeight: '500',
+      bgColor: 'white',
+    },
+    formControl: {
+      pt: '40px',
+    },
```
Comment (LoneRifle) [inline client/src/theme/components/AskForm.tsx:50]:
```suggestion
    },
    alert: {
      mt: '4px',
    },
```

File: client/src/pages/PostForm/AskForm/AskForm.component.tsx [hunk 3]
```diff
@@ -105,128 +117,122 @@ const AskForm = ({
...
+          rules={{
+            validate: (v) => !replaceEmptyRichTextInput(v) || v.length >= 30,
+          }}
+          render={({ field: { onChange, value, ref } }) => (
+            <RichTextEditor
+              onChange={onChange}
+              value={value}
+              editorRef={ref}
+              wrapperStyle={{ height: '148px' }}
+              editorStyle={{ height: `${148 - (26 + 6 * 2)}px` }}
```
Comment (LoneRifle) [inline client/src/pages/PostForm/AskForm/AskForm.component.tsx]: Consider extracting this into the Chakra theme, then do something like...
```suggestion
              {...styles.richTextEditor}
```

**Review by LoneRifle — APPROVED** [review]
lgtm otherwise!
